### PR TITLE
app-avalanche V0.8.0

### PR DESCRIPTION
**Pull request by neithanmo**
# Checklist

- [x ] App update process has been followed 
- [ x] Target branch is `develop` 
- [ x] Application version has been bumped 

changes:
- hybrid app to reduce binary size
- add support for EIP-712 ethereum messages
- add support for all ledger targets.
- general improvements

### CODE REVIEW

**Comment by tdejoigny-ledger** [comment]
@neithanmo ty for your PR.
But the PR cannot be merged in the current state. You need to have the required github workflows (CI) :
- to build the app for all supported targets (with our docker)
- to check our guideline (https://github.com/LedgerHQ/app-avalanche/blob/develop/.github/workflows/guidelines_enforcer.yml)
- to run the tests

I specify that the CI shall be green ;-)

**Comment by neithanmo** [comment]
Thanks @tdejoigny-ledger 

>     * to build the app for all supported targets (with our docker)

You mean that we should use yours instead of zondax's docker image?
```
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
```

**Comment by neithanmo** [comment]
Thanks @tdejoigny-ledger i am including the guidelines enforcer

**Comment by neithanmo** [comment]
@tdejoigny-ledger I added the guidelines enforcer in CI. The only issues are related with warnings coming from app-ethereum:

```
/__w/ledger-avalanche/ledger-avalanche/deps/ethereum/src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c:84:10: error: 'cx_ecdsa_verify' is deprecated [-Werror,-Wdeprecated-declarations]
    if (!cx_ecdsa_verify(&tokenKey,
         ^
/opt/nanox-secure-sdk/lib_cxng/include/lcx_ecdsa.h:193:1: note: 'cx_ecdsa_verify' has been explicitly marked deprecated here
DEPRECATED static inline bool cx_ecdsa_verify(const cx_ecfp_public_key_t *pukey,
^
/opt/nanox-secure-sdk/include/decorators.h:67:35: note: expanded from macro 'DEPRECATED'
#define DEPRECATED __attribute__((deprecated))
```

the use of deprecated functions in there.
Everything else seems to be OK with the enforce_guidelines flow

**Comment by tdejoigny-ledger** [comment]
> @tdejoigny-ledger I added the guidelines enforcer in CI. The only issues are related with warnings coming from app-ethereum:
> 
> ```
> /__w/ledger-avalanche/ledger-avalanche/deps/ethereum/src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c:84:10: error: 'cx_ecdsa_verify' is deprecated [-Werror,-Wdeprecated-declarations]
>     if (!cx_ecdsa_verify(&tokenKey,
>          ^
> /opt/nanox-secure-sdk/lib_cxng/include/lcx_ecdsa.h:193:1: note: 'cx_ecdsa_verify' has been explicitly marked deprecated here
> DEPRECATED static inline bool cx_ecdsa_verify(const cx_ecfp_public_key_t *pukey,
> ^
> /opt/nanox-secure-sdk/include/decorators.h:67:35: note: expanded from macro 'DEPRECATED'
> #define DEPRECATED __attribute__((deprecated))
> ```
> 
> the use of deprecated functions in there. Everything else seems to be OK with the enforce_guidelines flow


Hello @neithanmo , good to see that it's progressing well !

If I understand well you are using the ETH app as a dependency, which branch is used ?
I still don't see the workflows that build the different targets and the workflow that tests the app.

In addition, if you can rename this PR to have a more explicit description it could be good ;-)

**Comment by neithanmo** [comment]
> If I understand well you are using the ETH app as a dependency, which branch is used ? I still don't see the workflows that build the different targets and the workflow that tests the app.
> 

Yes, I rebased the latest changes from app-ethereum  `develop` branch (76e8690) , into our fork.
```
/opt/nanosplus-secure-sdk/include/decorators.h:67:35: note: expanded from macro 'DEPRECATED'
#define DEPRECATED __attribute__((deprecated))
                                  ^
/__w/ledger-avalanche/ledger-avalanche/deps/ethereum/src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c:84:10: error: 'cx_ecdsa_verify' is deprecated [-Werror,-Wdeprecated-declarations]
    if (!cx_ecdsa_verify(&tokenKey,
```    

> In addition, if you can rename this PR to have a more explicit description it could be good ;-)

done, I also found out why our tests were not being executed, and fixed it.

**Comment by neithanmo** [comment]
it seems our zemu/rust test are not running, not sure why tho.
it could be due to the other jobs, failing?

**Comment by tdejoigny-ledger** [comment]
> > If I understand well you are using the ETH app as a dependency, which branch is used ? I still don't see the workflows that build the different targets and the workflow that tests the app.
> 
> Yes, I rebased the latest changes from app-ethereum `develop` branch (76e8690) , into our fork.

Normally you should target `master `branch which is an official released version of the Ethereum app
cc: @apaillier-ledger @vforgeoux-ledger

**Comment by neithanmo** [comment]
> Normally you should target `master `branch which is an official released version of the Ethereum app cc: @apaillier-ledger @vforgeoux-ledger


switching to master branch triggers even more warnings, and would need to rework a bit the integration code as well.

```
/app/deps/ethereum/src_features/performPrivacyOperation/cmd_performPrivacyOperation.c:108:22: warning: invalid conversion specifi
er 'H' [-Wformat-invalid-specifier]
                 "%.*H",
                  ~~~^
/app/deps/ethereum/src_features/performPrivacyOperation/cmd_performPrivacyOperation.c:110:18: warning: data argument not used by 
format string [-Wformat-extra-args]
                 privateKeyData);
```
or

```
/app/deps/ethereum/src_features/provideDomainName/cmd_provide_domain_name.c:369:5: warning: 'cx_hash' is deprecated [-Wdeprecated
-declarations]
    cx_hash((cx_hash_t *) &sig_ctx->hash_ctx, CX_LAST, NULL, 0, hash, INT256_LENGTH);
```

listing a few.
have not updated this PR yet, because I  wanted to check it locally first.
Also, modifying our code to make our integration code compatible with the current master branch would likely require a new audit.

**Comment by tdejoigny-ledger** [comment]
> switching to master branch triggers even more warnings, and would need to rework a bit the integration code as well.

yes because we fixed some warnings on `develop ` branch, but this branch is still in development and has not been audited yet

> listing a few. have not updated this PR yet, because I wanted to check it locally first. Also, modifying our code to make our integration code compatible with the current master branch would likely require a new audit.

In any case, you used here as a dependency a fork of our ETH app, and this fork need to be audited (at least the delta from our master branch).

cc: @vforgeoux-ledger @apaillier-ledger 

BTW there is still no CI for build & tests ;-)

**Comment by neithanmo** [comment]
> > listing a few. have not updated this PR yet, because I wanted to check it locally first. Also, modifying our code to make our integration code compatible with the current master branch would likely require a new audit.

Thanks for the clarification makes sense, we updated to use master branch. 

> BTW there is still no CI for build & tests ;-)
 
they are running now:
- zemu tests
- rust unit and integration tests
- clippy and cargo fmt
- nanos/x/s2/stax build checks

**Comment by tdejoigny-ledger** [comment]
> > > listing a few. have not updated this PR yet, because I wanted to check it locally first. Also, modifying our code to make our integration code compatible with the current master branch would likely require a new audit.
> 
> Thanks for the clarification makes sense, we updated to use master branch.
> 
> > BTW there is still no CI for build & tests ;-)
> 
> they are running now:
> 
> * zemu tests
> * rust unit and integration tests
> * clippy and cargo fmt
> * nanos/x/s2/stax build checks

Ty. It seems better indeed. If I'm not wrong there is no CI to build NanoX/S+ and Stax (only NanoS). Perhaps I missed something?

**Comment by neithanmo** [comment]
> Ty. It seems better indeed. If I'm not wrong there is no CI to build NanoX/S+ and Stax (only NanoS). Perhaps I missed something?


We have built checks for all targets.  what you saw was an extra check we have for nanos, the app size, ensuring that the binary size does not exceed nanos capacity.
For zemu tests, they run on all targets as well nanos/x/s2/stax and for that we need to build the binaries the emulator uses

**Review by tdejoigny-ledger — APPROVED** [review]

**Pull request merged**
